-- ====================================================================
-- SUPABASE DATABASE SCHEMA FOR QUICKWASH 2.0 (MULTI-ROLE EDITION)
-- Run this script in the Supabase SQL Editor (Dashboard -> SQL Editor)
-- to set up the necessary tables and Row Level Security (RLS) policies.
-- ====================================================================

-- 1. PROFILES TABLE
-- Stores user profile information, linked to auth.users.
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    balance NUMERIC DEFAULT 0.0,
    address TEXT,
    role TEXT DEFAULT 'customer' CHECK (role IN ('customer', 'admin', 'delivery')),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- In case profiles already exists, ensure the role column is added
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'customer' CHECK (role IN ('customer', 'admin', 'delivery'));

-- Enable RLS for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policies for profiles
DROP POLICY IF EXISTS "Users can view all profiles" ON public.profiles;
CREATE POLICY "Users can view all profiles" 
    ON public.profiles FOR SELECT 
    TO authenticated
    USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
CREATE POLICY "Users can insert their own profile" 
    ON public.profiles FOR INSERT 
    WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile or admin updates any" ON public.profiles;
CREATE POLICY "Users can update their own profile or admin updates any" 
    ON public.profiles FOR UPDATE 
    TO authenticated
    USING (auth.uid() = id OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');


-- 2. CART ITEMS TABLE
-- Stores user cart items before checkout.
CREATE TABLE IF NOT EXISTS public.cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    category TEXT NOT NULL,
    item TEXT NOT NULL,
    emoji TEXT DEFAULT '👕',
    quantity INTEGER NOT NULL,
    services TEXT[] DEFAULT '{}',
    price NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS for cart_items
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;

-- Policies for cart_items
DROP POLICY IF EXISTS "Users can view their own cart items" ON public.cart_items;
CREATE POLICY "Users can view their own cart items" 
    ON public.cart_items FOR SELECT 
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own cart items" ON public.cart_items;
CREATE POLICY "Users can insert their own cart items" 
    ON public.cart_items FOR INSERT 
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own cart items" ON public.cart_items;
CREATE POLICY "Users can update their own cart items" 
    ON public.cart_items FOR UPDATE 
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own cart items" ON public.cart_items;
CREATE POLICY "Users can delete their own cart items" 
    ON public.cart_items FOR DELETE 
    USING (auth.uid() = user_id);


-- 3. ORDERS TABLE
-- Stores user orders placed.
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL UNIQUE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    delivery_boy_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    service_name TEXT NOT NULL,
    item_count INTEGER NOT NULL,
    price NUMERIC NOT NULL,
    status TEXT NOT NULL DEFAULT 'Processing',
    progress NUMERIC NOT NULL DEFAULT 0.1,
    date_time TEXT NOT NULL,
    emoji TEXT DEFAULT '🧺',
    items_detail TEXT,
    payment_method TEXT NOT NULL,
    pickup_date TEXT,
    pickup_time TEXT,
    dropoff_date TEXT,
    dropoff_time TEXT,
    cart_snapshot JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- In case orders already exists, ensure the delivery_boy_id column is added
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS delivery_boy_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL;

-- Enable RLS for orders
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Policies for orders
DROP POLICY IF EXISTS "Users can view their own, assigned, or all admin orders" ON public.orders;
CREATE POLICY "Users can view their own, assigned, or all admin orders" 
    ON public.orders FOR SELECT 
    TO authenticated
    USING (
        auth.uid() = user_id OR 
        auth.uid() = delivery_boy_id OR 
        (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
    );

DROP POLICY IF EXISTS "Users can insert their own orders" ON public.orders;
CREATE POLICY "Users can insert their own orders" 
    ON public.orders FOR INSERT 
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own, assigned, or all admin orders" ON public.orders;
CREATE POLICY "Users can update their own, assigned, or all admin orders" 
    ON public.orders FOR UPDATE 
    TO authenticated
    USING (
        auth.uid() = user_id OR 
        auth.uid() = delivery_boy_id OR 
        (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
    );


-- 4. WALLET TRANSACTIONS TABLE
-- Stores history of transactions (credits/debits).
CREATE TABLE IF NOT EXISTS public.wallet_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    type TEXT NOT NULL, -- 'credit' or 'debit'
    amount NUMERIC NOT NULL,
    description TEXT,
    date TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS for wallet_transactions
ALTER TABLE public.wallet_transactions ENABLE ROW LEVEL SECURITY;

-- Policies for wallet_transactions
DROP POLICY IF EXISTS "Users can view their own or all admin transactions" ON public.wallet_transactions;
CREATE POLICY "Users can view their own or all admin transactions" 
    ON public.wallet_transactions FOR SELECT 
    TO authenticated
    USING (
        auth.uid() = user_id OR 
        (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
    );

DROP POLICY IF EXISTS "Users can insert their own or all admin transactions" ON public.wallet_transactions;
CREATE POLICY "Users can insert their own or all admin transactions" 
    ON public.wallet_transactions FOR INSERT 
    TO authenticated
    WITH CHECK (
        auth.uid() = user_id OR 
        (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
    );


-- 5. NOTIFICATIONS TABLE
-- Stores notification logs for users.
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    order_id TEXT,
    status TEXT,
    type TEXT DEFAULT 'order_status',
    timestamp BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS for notifications
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Policies for notifications
DROP POLICY IF EXISTS "Users can view their own or all admin notifications" ON public.notifications;
CREATE POLICY "Users can view their own or all admin notifications" 
    ON public.notifications FOR SELECT 
    TO authenticated
    USING (
        auth.uid() = user_id OR 
        (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
    );

DROP POLICY IF EXISTS "Users can insert notifications" ON public.notifications;
CREATE POLICY "Users can insert notifications" 
    ON public.notifications FOR INSERT 
    TO authenticated
    WITH CHECK (true); -- Allow notifications to be sent by drivers/app when updating status
